version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 198653053291.dkr.ecr.us-east-1.amazonaws.com
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sed -i 's/FROM .*/FROM 687740418393.dkr.ecr.ap-south-1.amazonaws.com\/test-node:latest/' Dockerfile
      - docker build -t backend:latest .
      - docker tag backend:latest 198653053291.dkr.ecr.us-east-1.amazonaws.com/test-node:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 198653053291.dkr.ecr.us-east-1.amazonaws.com/test-node:latest
